version: '3.8'

services:
  nav-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nav-system
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # 生产环境变量
      - NODE_ENV=production
      - PORT=3000
      # 请在生产环境中更改这个密钥
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      # 时区设置
      - TZ=Asia/Shanghai
    volumes:
      # 持久化数据（如果需要）
      - nav-data:/app/data
      # 日志目录
      - nav-logs:/app/logs
    networks:
      - nav-network
    # 资源限制，适合OpenWrt环境
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx反向代理（可选，用于HTTPS和静态文件优化）
  nginx:
    image: nginx:alpine
    container_name: nav-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nav-logs:/var/log/nginx
    networks:
      - nav-network
    depends_on:
      - nav-system
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.2'
        reservations:
          memory: 32M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  nav-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  nav-data:
    driver: local
  nav-logs:
    driver: local